### ISSUE TITLE
Error retrieving RSS

### ISSUE THREAD

**Issue by Thoulah** [yiisoft/yii2-httpclient#104]
### What steps will reproduce the problem?
Retrieve RSS using this module

### What's expected?
RSS to be processed

### What do you get instead?
```
Exception 'Error' with message 'Class 'DOMDocument' not found'

in /homepages/htdocs/yii/vendor/yiisoft/yii2-httpclient/XmlParser.php:32
```

After enabling dom.so I get errors about 'Trying to get property of non-object'. Looks like last update breaks BC.

### Additional info

| Q                       | A
| ----------------------- | ---
| Yii version             |2.0.12
| Yii HTTP Client version |2.0.4
| PHP version             |7.1.6
| Operating system        |Debian 3.14.77-2~ui80+4 (2017-06-11) x86_64 GNU/Linux

**Comment by gonimar** [comment]
php-xml module

**Comment by Thoulah** [comment]
If you mean xml.so, that does not change anything.

```
public function actionRss($name, $url, $urlField = 'link') {
	$limit = is_int(Yii::$app->params['feedItemCount']) ? Yii::$app->params['feedItemCount'] : 25;
	$response = Webrequest::getUrl('', $url);
	if (!$response->isOK)
		return self::EXIT_CODE_ERROR;

	$count = 1;
	Feed::deleteAll(['feed' => $name]);
	foreach($response->data['channel']['item'] as $item) :
		$rssItem = new Feed();
		$rssItem->feed = $name;
		$rssItem->title = (string) $item->title; // Error on this line 'Trying to get property of non-object'
		$rssItem->url = (string) $item->$urlField;
		$rssItem->description = Yii::$app->formatter->cleanInput($item->description, false);
		$rssItem->time = strtotime($item->pubDate);
		$rssItem->save();

		if ($count++ === $limit)
			break;
	endforeach;

	return self::EXIT_CODE_NORMAL;
}
```

It was working before last update.

**Comment by klimov-paul** [comment]
Obviously you do not have [Document Object Model](http://php.net/manual/en/book.dom.php) PHP extension at your environment.

**Comment by Thoulah** [comment]
I already stated I enabled dom.so. My complaint is about BC

**Comment by klimov-paul** [comment]
DOM extension is a part of Yii2 requirements:
https://github.com/yiisoft/yii2/blob/master/framework/requirements/requirements.php#L99-LL105

Thus, I can not see any BC breaak here.

**Comment by Thoulah** [comment]
Again, DOM is enabled

**Comment by cebe** [comment]
@Thoulah post a stack tracce of the relevant error.

**Comment by Thoulah** [comment]
```
PHP Notice 'yii\base\ErrorException' with message 'Trying to get property of non-object'

in /homepages/htdocs/yii/mr42/commands/FeedController.php:30

Stack trace:
#0 /homepages/htdocs/yii/mr42/commands/FeedController.php(30): yii\base\ErrorHandler->handleError(8, 'Trying to get p...', '/homepages/31/d...', 30, Array)
#1 [internal function]: app\commands\FeedController->actionRss('ScienceDaily', 'https://rss.sci...', 'guid')
#2 /homepages/htdocs/yii/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /homepages/htdocs/yii/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array)
#4 /homepages/htdocs/yii/vendor/yiisoft/yii2/console/Controller.php(128): yii\base\Controller->runAction('rss', Array)
#5 /homepages/htdocs/yii/vendor/yiisoft/yii2/base/Module.php(523): yii\console\Controller->runAction('rss', Array)
#6 /homepages/htdocs/yii/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('feed/rss', Array)
#7 /homepages/htdocs/yii/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('feed/rss', Array)
#8 /homepages/htdocs/yii/vendor/yiisoft/yii2/base/Application.php(380): yii\console\Application->handleRequest(Object(yii\console\Request))
#9 /homepages/htdocs/yii/mr42/yii(15): yii\base\Application->run()
#10 {main}
```

**Comment by rob006** [comment]
@Thoulah It looks like problem in your controller. What is in line nr 30 in `FeedController`?

**Comment by Thoulah** [comment]
Code is in https://github.com/yiisoft/yii2-httpclient/issues/104#issuecomment-310839945

**Comment by rob006** [comment]
Yeah, without line numbers...

**Comment by Thoulah** [comment]
True, but the exact line is actually marked with a comment.

**Comment by cebe** [comment]
most likely `$item` is not an object then.

**Comment by Thoulah** [comment]
It used to be an object, until the update. Hence my BC compaint

**Comment by cebe** [comment]
I do not see how yii could have broken this. Does it work on the same data with an older version of this extension?

**Comment by klimov-paul** [comment]
See #102
