### ISSUE TITLE
Debug panel renders error on PHP 8.1

### ISSUE THREAD

**Issue by lacek** [yiisoft/yii2-httpclient#226]
### What steps will reproduce the problem?

Click "HTTP Requests" block in the debug toolbar.

### What's expected?

The detail view of "HTTP Client Requests" should be shown.

### What do you get instead?

An error page is shown with the following stacktrace:

```
yii\base\ErrorException: Implicit conversion from float 1677078278.632148 to int loses precision in /app/vendor/yiisoft/yii2-httpclient/src/debug/views/detail.php:29
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(8192, 'Implicit conver...', '/app/vendor/yii...', 29)
#1 /app/vendor/yiisoft/yii2-httpclient/src/debug/views/detail.php(29): date('H:i:s.', 1677078278.6321)
#2 [internal function]: yii\base\View->{closure}(Array, 0, 0, Object(yii\grid\DataColumn))
#3 /app/vendor/yiisoft/yii2/grid/DataColumn.php(250): call_user_func(Object(Closure), Array, 0, 0, Object(yii\grid\DataColumn))
#4 /app/vendor/yiisoft/yii2/grid/DataColumn.php(264): yii\grid\DataColumn->getDataCellValue(Array, 0, 0)
#5 /app/vendor/yiisoft/yii2/grid/Column.php(111): yii\grid\DataColumn->renderDataCellContent(Array, 0, 0)
#6 /app/vendor/yiisoft/yii2/grid/GridView.php(525): yii\grid\Column->renderDataCell(Array, 0, 0)
#7 /app/vendor/yiisoft/yii2/grid/GridView.php(494): yii\grid\GridView->renderTableRow(Array, 0, 0)
#8 /app/vendor/yiisoft/yii2/grid/GridView.php(358): yii\grid\GridView->renderTableBody()
#9 /app/vendor/yiisoft/yii2/widgets/BaseListView.php(160): yii\grid\GridView->renderItems()
#10 /app/vendor/yiisoft/yii2/grid/GridView.php(326): yii\widgets\BaseListView->renderSection('{items}')
#11 /app/vendor/yiisoft/yii2/widgets/BaseListView.php(135): yii\grid\GridView->renderSection('{items}')
#12 [internal function]: yii\widgets\BaseListView->yii\widgets\{closure}(Array)
#13 /app/vendor/yiisoft/yii2/widgets/BaseListView.php(138): preg_replace_callback('/{\\w+}/', Object(Closure), '{summary}\n{item...')
#14 /app/vendor/yiisoft/yii2/grid/GridView.php(301): yii\widgets\BaseListView->run()
#15 /app/vendor/yiisoft/yii2/base/Widget.php(146): yii\grid\GridView->run()
#16 /app/vendor/yiisoft/yii2-httpclient/src/debug/views/detail.php(15): yii\base\Widget::widget(Array)
#17 /app/vendor/yiisoft/yii2/base/View.php(347): require('/app/vendor/yii...')
#18 /app/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/app/vendor/yii...', Array)
#19 /app/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/app/vendor/yii...', Array, NULL)
#20 /app/vendor/yiisoft/yii2-httpclient/src/debug/HttpClientPanel.php(114): yii\base\View->render('@yii/httpclient...', Array)
#21 /app/vendor/yiisoft/yii2-debug/src/views/default/view.php(117): yii\httpclient\debug\HttpClientPanel->getDetail()
#22 /app/vendor/yiisoft/yii2/base/View.php(347): require('/app/vendor/yii...')
#23 /app/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/app/vendor/yii...', Array)
#24 /app/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/app/vendor/yii...', Array, Object(yii\debug\controllers\DefaultController))
#25 /app/vendor/yiisoft/yii2/base/Controller.php(407): yii\base\View->render('view', Array, Object(yii\debug\controllers\DefaultController))
#26 /app/vendor/yiisoft/yii2-debug/src/controllers/DefaultController.php(126): yii\base\Controller->render('view', Array)
#27 [internal function]: yii\debug\controllers\DefaultController->actionView('63f62f06941ee', 'httpclient')
#28 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#29 /app/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#30 /app/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('view', Array)
#31 /app/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('debug/default/v...', Array)
#32 /app/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#33 /app/frontend/web/index.php(18): yii\base\Application->run()
#34 {main}
```

### Additional info

| Q                       | A
| ----------------------- | ---
| Yii version             | 2.0.47
| Yii HTTP Client version | dev-master 6f23f75
| PHP version             | 8.1.16
| Operating system        | Docker image yiisoftware/yii2-php:8.1-apache on Ubuntu 20.04

A possible fix would be to explicitly cast `$timeInSeconds` to int for calling the `date` function in [detail.php](https://github.com/yiisoft/yii2-httpclient/blob/6f23f755f4414904700491271f7476c8952ad191/src/debug/views/detail.php#L29):

```diff
-return date('H:i:s.', $timeInSeconds) . sprintf('%03d', $millisecondsDiff);
+return date('H:i:s.', (int) $timeInSeconds) . sprintf('%03d', $millisecondsDiff);
```

**Comment by samdark** [comment]
Good catch. Do you have some time for a pull request?
