### ISSUE TITLE
Add CURLOPT_NOBODY for HEAD requests

### ISSUE THREAD

**Issue by AnatolyRugalev** [yiisoft/yii2-httpclient#33]
HEAD requests without curl option `CURLOPT_NOBODY` fails with timeout error:

```
Exception while handling command:
Curl error: #28 - Operation timed out after 9006 milliseconds with 0 out of 60497 bytes received in /app/vendor/yiisoft/yii2-httpclient/CurlTransport.php:51
#0 /app/vendor/yiisoft/yii2-httpclient/Client.php(213): yii\httpclient\CurlTransport->send(Object(yii\httpclient\Request))
#1 /app/vendor/yiisoft/yii2-httpclient/Request.php(302): yii\httpclient\Client->send(Object(yii\httpclient\Request))
```

Request code:

```php
$response = Yii::$app->httpclient->head($url)->send();
```

Working example:

```php
$response = Yii::$app->httpclient->head($filename, [], [
    CURLOPT_NOBODY => true,
])->send();
```

**Comment by klimov-paul** [comment]
Resolved by commit f17ba9780a3a45d9fa434981034a38be9394e27e
