### ISSUE TITLE
How to download a file from the remote server?

### ISSUE THREAD

**Issue by incrize** [yiisoft/yii2-httpclient#66]
The curl have an option CURLOPT_FILE.
Option is usable for download file without of memory usage trouble.
Will you implement something like this?

**Comment by Thoulah** [comment]
Can we have this implemented please?

**Comment by Thoulah** [comment]
I can't get this to work:
```
	public static function saveUrl(string $url, string $file): Response {
var_dump($url);
var_dump($file);
		$fh = fopen($file, 'w');
var_dump($fh);
		$client = new Client(['transport' => CurlTransport::class]);
var_dump($client);

		$response = $client->createRequest()
			->setMethod('GET')
			->setUrl($url)
			->setOutputFile($fh)
			->send();
		fclose($fh);
		return $response;
	}
```

Resulting dumps:
```
string(41) "http://standards-oui.ieee.org/oui/oui.csv"
string(86) "/htdocs/yii/mr42/mister42/../../../.cache/yii/mister42/oui.csv"
resource(68) of type (stream)
object(yii\httpclient\Client)#32 (10) {
  ["baseUrl"]=>
  NULL
  ["formatters"]=>
  array(0) {
  }
  ["parsers"]=>
  array(0) {
  }
  ["requestConfig"]=>
  array(0) {
  }
  ["responseConfig"]=>
  array(0) {
  }
  ["contentLoggingMaxSize"]=>
  int(2000)
  ["_transport":"yii\httpclient\Client":private]=>
  string(28) "yii\httpclient\CurlTransport"
  ["_events":"yii\base\Component":private]=>
  array(0) {
  }
  ["_eventWildcards":"yii\base\Component":private]=>
  array(0) {
  }
  ["_behaviors":"yii\base\Component":private]=>
  NULL
}
```
Looks good to me. But...:

```
Exception 'Error' with message 'Call to a member function send() on null'

in /htdocs/yii/mr42/mister42/models/Webrequest.php:53

Stack trace:
#0 /htdocs/yii/mr42/mister42/commands/FeedController.php(75): app\models\Webrequest::saveUrl('http://standard...', '/homepages/31/d...')
#1 [internal function]: app\commands\FeedController->actionOui()
#2 /htdocs/yii/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /htdocs/yii/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#4 /htdocs/yii/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('oui', Array)
#5 /htdocs/yii/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('oui', Array)
#6 /htdocs/yii/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('feed/oui', Array)
#7 /htdocs/yii/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('feed/oui', Array)
#8 /htdocs/yii/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))
#9 /htdocs/yii/mr42/App.php(23): yii\base\Application->run()
#10 /htdocs/yii/mr42/yii(4): App->__construct(true)
#11 {main}

```
